### ISSUE TITLE
Could not resolve host: someserver

### ISSUE THREAD

**Issue by sayo9394** [crops/extsdk-container#6]
Not sure if i'm doing this correctly.
```
sayoub@SSB-SAYOUB` MINGW64 /c/Program Files/Docker Toolbox
$ docker run --rm -it -v myvolume:/workdir crops/extsdk-container --url http://someserver/extensible_sdk_installer.sh
Attempting to download http://someserver/extensible_sdk_installer.sh

curl: (6) Could not resolve host: someserver
Unable to download "http://someserver/extensible_sdk_installer.sh".
```

**Comment by sayo9394** [comment]
Sorry for this silly NOOB issue reporting! i'll just close this and pretend nothing happened. 
Cheers.

**Comment by yzh0529** [comment]
how to reslove this problem，I have same trouble

**Comment by rewitt1** [comment]
Hi @yzh0529,

If you are getting that message from curl, then it is a name resolution issue. Check your url for typos. Either that, or you cannot access your dns server from inside the container you are running.
