### ISSUE TITLE
Advantages over ubuntu

### ISSUE THREAD

**Issue by mg262** [crops/extsdk-container#8]
Hi -- I'd be grateful to know what advantages extsdk has over simply starting an ubuntu instance and installing the Extensible Sdk from the shell script installer... ?  (Or using a Dockerfile based on ubuntu which installs the SDK, so that one has persistence.)

**Comment by rewitt1** [comment]
Hi @mg262,

The main advantage would be for allowing a user to only run one command to do all necessary setup and installation of the sdk. Other than that, you're right. You can replicate the same thing by using https://github.com/crops/poky-container.

And you could install it inside it using the Dockerfile as well. However, in that instance the container is going to grow to be quite a bit larger, and you'll be doing builds against whatever [storage-driver](https://docs.docker.com/storage/storagedriver/select-storage-driver/) docker is set up to use. And considering the number of files that can be created and destroyed during a build, the performance might not be what is typical.
